# Numpy 
NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and a wide range of mathematical functions to operate on these data structures. 

## Arrays
The core of NumPy is the ndarray object, which is a multidimensional array that allows for efficient computations.

In [1]:
import numpy as np

a = np.array([1, 2, 3])

#### create numpy array from 0 to 9

In [3]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a = np.arange(0, 10)
print("Original array:", a)

a = a + 1
print("After adding 1 to each element:", a)

a = a * 2
print("After multiplying each element by 2:", a)

a = a - 1
print("After subtracting 1 from each element:", a)

a = a / a
print("After dividing each element by itself:", a)


Original array: [0 1 2 3 4 5 6 7 8 9]
After adding 1 to each element: [ 1  2  3  4  5  6  7  8  9 10]
After multiplying each element by 2: [ 2  4  6  8 10 12 14 16 18 20]
After subtracting 1 from each element: [ 1  3  5  7  9 11 13 15 17 19]
After dividing each element by itself: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
a = np.arange(0, 10)
print("Original array:", a)

# Accessing the 5th element (index 5)
print("5th element:", a[5])

# Slicing from index 3 to 7 (inclusive of 3, exclusive of 7)
print("Elements from index 3 to 7:", a[3:7])


Original array: [0 1 2 3 4 5 6 7 8 9]
5th element: 5
Elements from index 3 to 7: [3 4 5 6]


In [11]:
a = np.arange(0, 10)
print("Original array:", a)

# Checking the shape of the array
print("Shape of the array:", a.shape)

# Reshaping the array into a 2x5 matrix
a = a.reshape(2, 5)
print("Reshaped array (2x5):\n", a)

Original array: [0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [15]:
a = np.arange(10).reshape(2, 5)
b = np.arange(1,6)
print(a+b)

[[ 1  3  5  7  9]
 [ 6  8 10 12 14]]


In [16]:
a = np.arange(1,6)
print(np.sqrt(a))
print(np.exp(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [20]:
import numpy as np

# Creating a 1D array a with values from 0 to 9
a = np.arange(10)

# Computing the minimum, maximum, and mean
min_value = a.min()
max_value = a.max()
mean_value = a.mean()

# Printing the min, max, and mean
print("Min:", min_value, "Max:", max_value, "Mean:", mean_value)

# Computing and printing the sum of the array
sum_value = a.sum()
print("Sum:", sum_value)


Min: 0 Max: 9 Mean: 4.5
Sum: 45


In [22]:
# Creating a 2x5 matrix a
a = np.arange(10).reshape(2, 5)
print("Original Matrix:\n", a)

# Summing along the rows (axis=1)
row_sums = a.sum(axis=1)
print("Sum along the rows:", row_sums)

# Computing the mean along the columns (axis=0)
column_means = a.mean(axis=0)
print("Mean along the columns:", column_means)


Original Matrix:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Sum along the rows: [10 35]
Mean along the columns: [2.5 3.5 4.5 5.5 6.5]


In [25]:
# Creating a 1D array a with values from 0 to 9
a = np.arange(10)

# Applying Boolean masking to filter elements greater than 5
filtered_array = a[a > 5]
print("Filtered array (elements > 5):", filtered_array)


Filtered array (elements > 5): [6 7 8 9]


In [30]:
import numpy as np

# Step 1: Create a 3x4 matrix with random integers from 1 to 100
a = np.random.randint(1, 101, size=(3, 4))
print("Original Matrix:\n", a)

# Step 2: Print the data type of the array
print("Data type of the original array:", a.dtype)

# Step 3: Convert the integer array to a structured array with two fields
# Define the structured array dtype
dtype = [('int_value', 'i4'), ('float_value', 'f4')]

# Create the structured array
structured_array = np.empty(a.shape[0], dtype=dtype)

Original Matrix:
 [[ 72 100  48  91]
 [ 36  92  83  56]
 [ 64  10   6  54]]
Data type of the original array: int32
